### ISSUE TITLE
when to release a new version to support 'playoff'?

### ISSUE THREAD

**Issue by zuoRambo** [mangix/nbalive#2]
I get the  "no games this day" message when run the cmd file today [2015-05-05] ,what happend?

**Comment by lcat** [comment]
http://115.159.33.31/nba/schedule/fetch 

```
{
    "code": 200,
    "data": []
}
```

**Comment by zuoRambo** [comment]
@lcat so,what do you mean?

**Comment by mangix** [comment]
sorry , coming soon...  . I'll update this week !

**Comment by zuoRambo** [comment]
@mangix thanks a lot,that will be cool & awesome! Another suggestion is add sina scene...

**Comment by mangix** [comment]
@zuoRambo Game list and statistic is available now . But I am not sure about the live data . I will check this tomorrow morning.
